import { useEffect } from 'react'
import axios from '../config/axios'
import { initializeSocket, receiveMessage } from '../config/socket'
import { cleanAIJson } from '../utils/project/aiHelpers'

/**
 * useProjectSocket — handles:
 *  - Socket initialization + incoming message handling
 *  - Project data loading (fileTree, messages)
 *  - Collaborator list fetching
 *  - File tree saving
 */
export function useProjectSocket({
    project,
    currentFile,
    setProject,
    setFileTree,
    setMessages,
    setUsers,
    setRunMeta,
    openFile,
    logToTerminal,
    pushNotification,
    setIsTerminalOpen,
}) {
    useEffect(() => {
        if (!project) return

        initializeSocket(project._id)

        receiveMessage('project-message', data => {
            console.log('msg:', data)

            if (data.sender._id === 'ai') {
                try {
                    const parsed = JSON.parse(cleanAIJson(data.message))

                    if (parsed.fileTree && Object.keys(parsed.fileTree).length > 0) {
                        const ft = parsed.fileTree
                        setFileTree(ft)
                        const firstFile = Object.keys(ft)[0]
                        if (firstFile) openFile(firstFile)

                        const fileCount = Object.keys(ft).length
                        pushNotification(`${fileCount} file${fileCount > 1 ? 's' : ''} generated by AI`, 'success', 'Files Created')
                        logToTerminal(`AI generated ${fileCount} file(s): ${Object.keys(ft).join(', ')}`, 'success')
                        setIsTerminalOpen(true)
                    }

                    if (parsed.buildCommand || parsed.startCommand) {
                        setRunMeta({
                            buildCommand: parsed.buildCommand || null,
                            startCommand: parsed.startCommand || null,
                        })
                        logToTerminal(
                            `Run commands detected — click ▶ Run: ${parsed.startCommand?.mainItem} ${parsed.startCommand?.commands?.join(' ')}`,
                            'info'
                        )
                    }
                } catch (e) {
                    console.warn('AI response was not JSON:', e)
                }
            }

            setMessages(prev => [...prev, data])
        })

        // Load saved project data
        axios.get(`/projects/get-project/${project._id}`).then(res => {
            setProject(res.data.project)
            const ft = res.data.project.fileTree || {}
            setFileTree(ft)
            const keys = Object.keys(ft)
            if (keys.length > 0) openFile(keys[0])
            logToTerminal(`Project "${res.data.project.name}" loaded — ${keys.length} file(s)`, 'system')

            // Restore chat history
            const savedMessages = res.data.project.messages || []
            if (savedMessages.length > 0) {
                setMessages(savedMessages.map(m => ({ sender: m.sender, message: m.message })))
                logToTerminal(`Restored ${savedMessages.length} message(s) from history`, 'system')
            }

            // Auto-detect runMeta from saved fileTree
            if (ft['package.json']) {
                try {
                    const pkg = JSON.parse(ft['package.json'].file.contents)
                    const startCmd = pkg.scripts?.start
                        ? { mainItem: 'npm', commands: ['run', 'start'] }
                        : pkg.scripts?.dev
                            ? { mainItem: 'npm', commands: ['run', 'dev'] }
                            : { mainItem: 'node', commands: [pkg.main || 'index.js'] }
                    setRunMeta({
                        buildCommand: { mainItem: 'npm', commands: ['install'] },
                        startCommand: startCmd,
                    })
                    logToTerminal('Run commands auto-detected from package.json — click ▶ Run', 'info')
                } catch { /* non-parseable package.json — ignore */ }
            }
        })

        axios.get('/users/all').then(res => setUsers(res.data.users)).catch(console.log)

    }, []) // eslint-disable-line react-hooks/exhaustive-deps

    // ── Save file tree to backend ─────────────────────────────────────────
    function saveFileTree(ft) {
        axios.put('/projects/update-file-tree', {
            projectId: project._id,
            fileTree: ft,
        }).then(() => {
            pushNotification(`${currentFile} saved`, 'info')
            logToTerminal(`File saved: ${currentFile}`, 'info')
        }).catch(err => {
            console.log(err)
            pushNotification('Failed to save file', 'error', 'Save Error')
        })
    }

    return { saveFileTree }
}
